In [1]:
import pandas

In [2]:
df1 = pandas.read_csv('Documents/Остров1012/Dataset 10.21/products_dns_sorted.csv')

In [3]:
df1[:3]

product_id                       category_id  \
0  81F1005056A615EF11E309FFE937AB5C  B24E00155D030B1F11E270E6F5145C0B   
1  81F1005056A615EF11E309FFE937AB5D  B24E00155D030B1F11E270E6F5145C0B   
2  81F1005056A615EF11E309FFE937AB5E  B24E00155D030B1F11E270E6F5145C0B   

                                         description  
0  Зеркало внутрисалонное ВЕГА-330 [330 мм; панор...  
1  Зеркало внутрисалонное ВЕГА-330 антиблик [330 ...  
2  Зеркало внутрисалонное СИРИУС-300 [300 мм; пан...

In [4]:
df1['category_id']

0         B24E00155D030B1F11E270E6F5145C0B
1         B24E00155D030B1F11E270E6F5145C0B
2         B24E00155D030B1F11E270E6F5145C0B
3         B24E00155D030B1F11E270E6F5145C0B
4         B24E00155D030B1F11E270E6F5145C0B
5         B24E00155D030B1F11E270E6F5145C0B
6         B24E00155D030B1F11E270E6F5145C0B
7         B24E00155D030B1F11E270E6F5145C0B
8         B24E00155D030B1F11E270E6F5145C0B
9         B24E00155D030B1F11E270E6F5145C0B
10        B24E00155D030B1F11E270E6F5145C0B
11        B24E00155D030B1F11E270E6F5145C0B
12        B24E00155D030B1F11E270E6F5145C0B
13        B24E00155D030B1F11E270E6F5145C0B
14        B24E00155D030B1F11E270E6F5145C0B
15        B24E00155D030B1F11E270E6F5145C0B
16        B24E00155D030B1F11E270E6F5145C0B
17        B24E00155D030B1F11E270E6F5145C0B
18        B24E00155D030B1F11E270E6F5145C0B
19        B24E00155D030B1F11E270E6F5145C0B
20        B24E00155D030B1F11E270E6F5145C0B
21        B24E00155D030B1F11E270E6F5145C0B
22        B24E00155D030B1F11E270E6F5145C0B
23        B

In [5]:
len(df1['category_id'].unique())

914

In [6]:
? len

In [7]:
from sklearn.feature_extraction.text import CountVectorizer #Подключение класса CountVectorizer из модуля sklearn.feature_extraction.text

In [8]:
varCV=CountVectorizer() #определение объекта

In [9]:
df2=df1.dropna()

In [10]:
varCH=varCV.fit_transform(df2['description']) #

In [11]:
s = ['set path name happy', 
    'road lost route',
    'make me happy happy ']

In [12]:
x = varCV.fit_transform(df2['description'])

In [13]:
x

<559362x308719 sparse matrix of type '<type 'numpy.int64'>'
	with 6125987 stored elements in Compressed Sparse Row format>

In [14]:
#x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
s.get_feature_names()

AttributeError: 'list' object has no attribute 'get_feature_names'

In [52]:
varCV.get_feature_names()

[u'00',
 u'000',
 u'0000',
 u'00000',
 u'000000',
 u'0000000ps',
 u'0000001',
 u'0000002',
 u'00000025',
 u'00000082',
 u'000001',
 u'00000173',
 u'00000176',
 u'000002',
 u'00000322',
 u'00000332',
 u'00000375',
 u'00000380',
 u'00000381',
 u'00000383',
 u'00000384',
 u'00000385',
 u'00000387',
 u'00000388',
 u'00000389',
 u'00000390',
 u'00000393',
 u'00000394',
 u'00000395',
 u'00000396',
 u'00000397',
 u'00000398',
 u'00000399',
 u'000004',
 u'00000405',
 u'00000408',
 u'00000409',
 u'00000410',
 u'00000411',
 u'00000416',
 u'00000418',
 u'00000419',
 u'00000422',
 u'00000424',
 u'00000425',
 u'00000426',
 u'00000472',
 u'00000474',
 u'00000477',
 u'00000478',
 u'00000479',
 u'00000480',
 u'00000486',
 u'00000489',
 u'000005',
 u'00000588',
 u'00000611',
 u'00000614',
 u'00000682',
 u'00000683',
 u'00000685',
 u'00000686',
 u'00000880',
 u'00000964',
 u'00000969',
 u'00000970',
 u'00001',
 u'00001044',
 u'00001045',
 u'00001046',
 u'00001054',
 u'00001095',
 u'00001097',
 u'0000109

In [53]:
testX = df2['description'][::2]

In [54]:
trainX = df2['description'][1::2]

In [55]:
testY = df2['category_id'][::2]

In [56]:
trainY = df2['category_id'][1::2]

In [57]:
# testX

In [58]:
cnt_vec = CountVectorizer()
trainX = cnt_vec.fit_transform(trainX)

testX = cnt_vec.transform(testX)

In [59]:
# trainX = CountVectorizer().fit_transform(trainX)

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [61]:
classifier = MultinomialNB().fit(trainX,trainY)

In [62]:
classifier

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [63]:
print("{0:.4f}".format(classifier.score(trainX, trainY)))

0.8779


In [64]:
print("{0:.4f}".format(classifier.score(testX, testY)))

0.8568


In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
dec_tree = DecisionTreeClassifier().fit(trainX, trainY)

print("{0:.4f}".format(dec_tree.score(trainX, trainY)))
print("{0:.4f}".format(dec_tree.score(testX, testY)))

0.9992
0.9531


In [68]:
from sklearn.metrics import confusion_matrix

In [71]:
predicted = dec_tree.predict(testX)

In [72]:
confusion_matrix(testY, predicted)

array([[  34,    0,    0, ...,    0,    0,    0],
       [   0,  972,    1, ...,    0,    0,    0],
       [   0,    3,  134, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ..., 1694,    0,    0],
       [   0,    0,    0, ...,    0,  324,    0],
       [   0,    0,    0, ...,    0,    0,  269]])

In [75]:
counts = df2["category_id"].value_counts()

In [76]:
counts

B24E00155D030B1F11E270E6F5145C0B    42304
938D00155D03330D11E7945E3C3A3C2D    29982
B24E00155D030B1F11E270E6F5145BFB    27129
89CB00155D03120211E47FCF329B18E8    23046
B24E00155D030B1F11E270E6F5145C74    17482
B24E00155D030B1F11E270E6FD72100D     7204
90BF00155D03120211E47ABC9E8CFEC9     5659
B24E00155D030B1F11E270E6FD721041     5511
B24E00155D030B1F11E270E6FD72105A     5017
B24E00155D030B1F11E270E6FD721046     4734
9DC500155D03330D11E84A9DD6899605     4661
82D400155D030B1F11E27E4824F0D334     4415
B24E00155D030B1F11E270E6FD721058     4308
B24E00155D030B1F11E270E6FD721008     4209
B24E00155D030B1F11E270E6FD72100F     4031
B24E00155D030B1F11E270E6F5145C73     3990
858400155D03361B11E4819DFCD38E2D     3848
B24E00155D030B1F11E270E6F5145C40     3745
B24E00155D030B1F11E270E6FD721043     3708
B78C00155D03330711E647D81D5EE2A7     3623
B24E00155D030B1F11E270E6F5145C6C     3548
9B8500155D030B1F11E2D896F5BE1C59     3501
B24E00155D030B1F11E270E6F5145C03     3484
B24E00155D030B1F11E270E6FD721035  

In [77]:
index = counts.index[counts>=10000]

In [78]:
index

Index([u'B24E00155D030B1F11E270E6F5145C0B',
       u'938D00155D03330D11E7945E3C3A3C2D',
       u'B24E00155D030B1F11E270E6F5145BFB',
       u'89CB00155D03120211E47FCF329B18E8',
       u'B24E00155D030B1F11E270E6F5145C74'],
      dtype='object')

In [79]:
df_cut = df2[df2.isin(index).values]

In [80]:
df_cut

product_id                       category_id  \
0       81F1005056A615EF11E309FFE937AB5C  B24E00155D030B1F11E270E6F5145C0B   
1       81F1005056A615EF11E309FFE937AB5D  B24E00155D030B1F11E270E6F5145C0B   
2       81F1005056A615EF11E309FFE937AB5E  B24E00155D030B1F11E270E6F5145C0B   
3       81F1005056A615EF11E309FFE937AB5F  B24E00155D030B1F11E270E6F5145C0B   
4       81F1005056A615EF11E309FFE937AB60  B24E00155D030B1F11E270E6F5145C0B   
5       81F1005056A615EF11E309FFE937AB61  B24E00155D030B1F11E270E6F5145C0B   
6       81F1005056A615EF11E309FFE937AB62  B24E00155D030B1F11E270E6F5145C0B   
7       81F1005056A615EF11E309FFE937AB63  B24E00155D030B1F11E270E6F5145C0B   
8       81F1005056A615EF11E309FFE937AB84  B24E00155D030B1F11E270E6F5145C0B   
9       81F1005056A615EF11E309FFE937AB87  B24E00155D030B1F11E270E6F5145C0B   
10      81F1005056A615EF11E309FFE937AB8A  B24E00155D030B1F11E270E6F5145C0B   
11      81F1005056A615EF11E309FFE937AB8B  B24E00155D030B1F11E270E6F5145C0B   
12      81F1005056A615EF11E309FFE937AB8C  B24E00155D030B1F11E270E6F5145C0B   
13      81F1005056A615EF11E309FFE937AB8D  B24E00155D030B1F11E270E6F5145C0B   
14      81F1005056A615EF11E30A380A111CAD  B24E00155D030B1F11E270E6F5145C0B   
15      81F1005056A615EF11E30A380A111CAE  B24E00155D030B1F11E270E6F5145C0B   
16      81F1005056A615EF11E30A380A111CAF  B24E00155D030B1F11E270E6F5145C0B   
17      81F1005056A615EF11E30A380A111CB0  B24E00155D030B1F11E270E6F5145C0B   
18      81F1005056A615EF11E30A380A111CB1  B24E00155D030B1F11E270E6F5145C0B   
19      8292005056A4699B11E3C460926A1F6F  B24E00155D030B1F11E270E6F5145C0B   
20      8292005056A4699B11E3C460926A1F71  B24E00155D030B1F11E270E6F5145C0B   
21      8292005056A4699B11E3C460926A1F73  B24E00155D030B1F11E270E6F5145C0B   
22      8292005056A4699B11E3C460926A1F75  B24E00155D030B1F11E270E6F5145C0B   
23      8292005056A4699B11E3C463FD771B26  B24E00155D030B1F11E270E6F5145C0B   
24      8292005056A4699B11E3C463FD771B28  B24E00155D030B1F11E270E6F5145C0B   
25      8308005056A615EF11E378BEDE178939  B24E00155D030B1F11E270E6F5145C0B   
26      8308005056A615EF11E37BE9E44C7534  B24E00155D030B1F11E270E6F5145C0B   
27      8308005056A615EF11E37D745C9B954C  B24E00155D030B1F11E270E6F5145C0B   
28      8308005056A615EF11E37D745C9B954D  B24E00155D030B1F11E270E6F5145C0B   
29      8308005056A615EF11E37D745C9B954E  B24E00155D030B1F11E270E6F5145C0B   
...                                  ...                               ...   
139952  BEA900155D03330711E5CA592F67325C  B24E00155D030B1F11E270E6F5145C74   
139953  BEA900155D03330711E5CA592F67325D  B24E00155D030B1F11E270E6F5145C74   
139954  BEA900155D03330711E5CA592F67325E  B24E00155D030B1F11E270E6F5145C74   
139955  BEA900155D03330711E5CA592F67325F  B24E00155D030B1F11E270E6F5145C74   
139956  BEA900155D03330711E5CA592F673260  B24E00155D030B1F11E270E6F5145C74   
139957  BECA00155D030B1F11E2C65265899DD1  B24E00155D030B1F11E270E6F5145C74   
139958  BECA00155D030B1F11E2C670F49511B6  B24E00155D030B1F11E270E6F5145C74   
139959  BECA00155D030B1F11E2C670F49511C2  B24E00155D030B1F11E270E6F5145C74   
139960  BECA00155D030B1F11E2C670F49511C3  B24E00155D030B1F11E270E6F5145C74   
139961  BECA00155D030B1F11E2C670F49511C6  B24E00155D030B1F11E270E6F5145C74   
139962  BECA00155D030B1F11E2C670F49511C7  B24E00155D030B1F11E270E6F5145C74   
139963  BECA00155D030B1F11E2C723ED579970  B24E00155D030B1F11E270E6F5145C74   
139964  BECA00155D030B1F11E2C723ED579971  B24E00155D030B1F11E270E6F5145C74   
139965  BECA00155D030B1F11E2C723ED579972  B24E00155D030B1F11E270E6F5145C74   
139966  BECA00155D030B1F11E2C723ED579973  B24E00155D030B1F11E270E6F5145C74   
139967  BECA00155D030B1F11E2C723ED57997D  B24E00155D030B1F11E270E6F5145C74   
139968  BECA00155D030B1F11E2C723ED57997E  B24E00155D030B1F11E270E6F5145C74   
139969  BECA00155D030B1F11E2CCA58D304C24  B24E00155D030B1F11E270E6F5145C74   
139970  BECA00155D030B1F11E2CCA58D304C25  B24E00155D030B1F11E270E6F5145C74   
139971  BECA00155D030B1F11E2CCA58D304C26  B24E00155D

In [91]:
testX_cut = df_cut['description'][::2]

In [92]:
trainX_cut = df_cut['description'][1::2]

In [93]:
testY_cut = df_cut['category_id'][::2]

In [94]:
trainY_cut = df_cut['category_id'][1::2]

In [95]:
cnt_vec_cut = CountVectorizer()
trainX_cut = cnt_vec_cut.fit_transform(trainX_cut)

testX_cut = cnt_vec_cut.transform(testX_cut)

In [96]:
classifier_cut = MultinomialNB().fit(trainX_cut,trainY_cut)

In [97]:
print("{0:.4f}".format(classifier_cut.score(trainX_cut, trainY_cut)))

0.9971


In [98]:
print("{0:.4f}".format(classifier_cut.score(testX_cut, testY_cut)))

0.9966


In [100]:
predicted_cut = classifier_cut.predict(testX_cut)

In [101]:
confusion_matrix(testY_cut, predicted_cut)

array([[11523,     0,     0,     0,     0],
       [    3, 14869,    20,    26,    73],
       [    0,     3, 13556,     6,     0],
       [    1,    43,     2, 21056,    50],
       [    0,     8,     0,     1,  8732]])

In [115]:
# df_cut[df_cut.isin(df_cut.index[predicted_cut != testY_cut]).values]
testX__ = df_cut['description'][::2]
testX__[predicted_cut != testY_cut]

30        Пакеты для колес TechnoPoint [R12 - R22; 110 x...
32            Утеплитель двигателя АвтоОдеяло №1 [160x90см]
34            Утеплитель двигателя АвтоОдеяло №3 [130x90см]
70                   Сетка для ниш Nevod СЕТКА-01 [55-25см]
72                    Сетка карман Nevod СЕТКА-05 [90-30см]
74        Сетка напольная классическая Nevod СЕТКА-03 [9...
80        Очки для водителей SPGlasses AS021 (витринный ...
82        Очки для водителей SPGlasses AD047 (витринный ...
90                     Насос ножной KOTO CP 300 [одинарный]
92        Стяжка для груза Phantom PH6422 [2.5 м; трещетка]
94        Чехлы для колес Phantom PH5410 [компл. на 4 ко...
7092      Стяжка для груза ALCA 5м; для крепления грузов...
7094      Стяжка для груза AUTOVIRAZH 2х2;5м; для крепле...
7096                  Стяжка для груза KIOKI CF18  3м; 35мм
7098                        Стяжка для груза MAAS/СФЕРА 10м
7102        Приёмник GPS Expert Navigation EN-316 Bluetooth
7104                    Приёмник GPS Glo